apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  ML_ENDPOINT: "http://backend-service:8000/predict"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: "aGFpZGhp"        
  POSTGRES_PASSWORD: "aGFpZGhp"
  POSTGRES_DB: "cGF0aWVudF9kYXRhYmFzZQo="  
